### PR TITLE
Add jitdumps

### PR DESCRIPTION
**Pull request by maxbrunet**
Add jitdumps and their JSON snapshots for parca-dev/parca-agent#1051

In most cases, these dumps were obtained with:

```shell
docker run --name <runtime>-example parca-demo:<runtime>
docker cp <runtime>-example:/tmp/jit-1.dump <runtime>.dump
```

Their JSON counterparts were generated by the tests that I will push to the agent PR once this one merged. 

Let me know if you'd like to structure things differently.

### CODE REVIEW

**Comment by javierhonduco** [comment]
This is very nice! Could you add a script and some build entry in the Makefile to (re)generate this?

**Comment by maxbrunet** [comment]
> This is very nice! Could you add a script and some build entry in the Makefile to (re)generate this?

This is done from the Go tests, you'll see once I push the tests to the other PR. Happy to iterate later if needed, but need to merge this one first

**Comment by javierhonduco** [comment]
Makes sense, thanks for explaining

**Review by javierhonduco — APPROVED** [review]

**Comment by maxbrunet** [comment]
Here parca-dev/parca-agent@5e5d9b150e35fc14042c047870a360b40129b158

**Pull request merged**
