### PR TITLE
Add LLVM/Jitlink testdata

### PR DESCRIPTION
**Pull request by vchuravy**
@pchintalapudi is working on add `jitdump` support to the new `JITLink` in LLVM.
This will be equivalent to what Julia and others will emit in the future.

New here is the support for unwind info. Does that unwind info look correct/helpful for parca?

### CODE REVIEW

**Comment by javierhonduco** [comment]
My apologies -- I somehow missed this. It's great that `JITLink` is getting support for this! 

> New here is the support for unwind info. Does that unwind info look correct/helpful for parca?

Right now we only support reading this info from "normal" executables, not JITdump so support for it will have to be added. 

I'm more than happy to merge as-is, but out of curiosity, what's the current state of the unwind information quality? I assume is reuses the same machinery that LLVM uses for the ahead-of-time binaries, right?

**Comment by javierhonduco** [comment]
Could you add some references perhaps to the commit message on the format / spec of `JITLink`?

**Review by javierhonduco — APPROVED** [review]

**Comment by vchuravy** [comment]
>  what's the current state of the unwind information quality? I assume is reuses the same machinery that LLVM uses for the ahead-of-time binaries, right?

Maybe @pchintalapudi has a better answer, but right now I don't think we now. I will have to find a client that makes actual use of it and we used parca partially to confirm that we got the rest of the format right.

**Comment by javierhonduco** [comment]
Sounds good -- happy to help with anything unwinding related in Parca Agent in case you want to go ahead and implement support for this! :)

**Pull request merged**
