### PR TITLE
port toy JIT to arm

### PR DESCRIPTION
**Pull request by umanwizard**

### CODE REVIEW

**Comment by gnurizen** [comment]
LGTM!

**Comment by brancz** [comment]
Not sure how that conflict happened, but it doesn't seem easily resolvable through the GitHub UI, can you fix that?

Then lgtm! Nice work!

**Comment by umanwizard** [comment]
@kakkoyun , do you know what's going on? Apparently the entire makefile was rewritten, but this was never picked up in the parca-agent repo...

**Comment by kakkoyun** [comment]
@umanwizard This looks super weird. The makefile is old. We don't use this version anymore. The builds happen here: https://github.com/parca-dev/testdata/blob/main/build.go

`Makefile` is just a proxy through the devbox to the mage build file.

**Comment by kakkoyun** [comment]
This PR https://github.com/parca-dev/testdata/pull/27 broke the git or github 🙃

**Comment by umanwizard** [comment]
What do you mean by "we don't use this version" ? The version of this repo linked in `parca-agent` is [7669417](https://github.com/parca-dev/testdata/commit/766941752c489b83012676dbb628333fb360c357) .

All changes since then have not been brought in to parca-agent, which is why I'm developing on top of what is there, rather than what happens to be in the tip of master in the testdata repo.

I don't know why changes were made in this repo and never picked up in parca-agent (in fact, I don't know why they are separate repos at all).

**Comment by kakkoyun** [comment]
> What do you mean by "we don't use this version" ? The version of this repo linked in `parca-agent` is [7669417](https://github.com/parca-dev/testdata/commit/766941752c489b83012676dbb628333fb360c357) .
> 
> All changes since then have not been brought in to parca-agent, which is why I'm developing on top of what is there, rather than what happens to be in the tip of master in the testdata repo.
> 
> I don't know why changes were made in this repo and never picked up in parca-agent (in fact, I don't know why they are separate repos at all).

We should have synced the tip of the main. And I thought this was done. @Sylfrena, didn't we finish that work?

In any case, I think we should make it work with the tip of the main. This enables us to have multi-arch binaries for testing.

**Comment by umanwizard** [comment]
I would rather not take on a requirement for Docker OR this devenv thing to develop the agent. Currently I'm not using either of them. Is it possible to make that work in the new system (i.e., make the testdata buildable using only normal local tools) ?

**Comment by Sylfrena** [comment]
> We should have synced the tip of the main. And I thought this was done. @Sylfrena, didn't we finish that work?

Nah, I never pulled in the updated testdata into the agent. That caused some tests in the agent to fail and then the extra-leaf frame error we were seeing caused further confusion(now we know this is an agent issue) so I just wanted to make sure we are  building and committing the right binaries.

> I would rather not take on a requirement for Docker OR this devenv thing to develop the agent. Currently I'm not using either of them. Is it possible to make that work in the new system (i.e., make the testdata buildable using only normal local tools) ?

I understand where you are coming from, but I would like to keep the devenv thing and the docker thing. Once set up, both make the workflow considerably easier, especially when it comes to multiarch builds.

However, I would be okay with adding newer `make` targets (on top of the existing zig and magefile toolchain) to build it using "normal" local tools.

**Pull request closed without merging**
